### PR TITLE
Script to download all of the images

### PR DESCRIPTION
**Pull request by johnletey**
@nikitavoloboev How does this look?

### CODE REVIEW

**Comment by johnletey** [comment]
@nikitavoloboev Any thoughts?

**Comment by nikitavoloboev** [comment]
Will try in a bit, not on mac now :)

**Comment by nikitavoloboev** [comment]
Awesome 🎊

Thanks for the PR

**Comment by nikitavoloboev** [comment]
Although I think I would maybe generalize this into a tool so as to not keep the code in the repo here (want to keep the repo for markdown only).

@johnletey Do you want to maybe make a repo for this little utility (it's your code after all 😊)

**Comment by nikitavoloboev** [comment]
Also it's not clear to me where it loads the results to. I thought it'd be `imgs` file at the dir I call the tool from but I see no such file (although I haven't ran the process to completion). It actually takes a surprisingly long time to retrieve each result. Ideally it would parallelize its work to finish faster. Not sure why it takes such long time.

**Comment by nikitavoloboev** [comment]
Oh I see now it puts the images to `imgs/` dir. The slowness and generalizing this so I don't keep the code in this repo is still something I want to do.

**Comment by johnletey** [comment]
> Do you want to maybe make a repo for this little utility (it's your code after all 😊)

Sure, I'll do that sometime tomorrow. I'm thinking of making it into a CLI tool ... I'll keep you posted

> Ideally it would parallelize its work to finish faster.

Definitely! When I create my own repo, I'll try to optimise it and make it faster

@nikitavoloboev When you merged this, it automatically closed #25 ... do you want to reopen the issue as it isn't resolved yet?

**Comment by nikitavoloboev** [comment]
Reopened :)

**Comment by nikitavoloboev** [comment]
> When I create my own repo, I'll try to optimise it and make it faster

Any progress on that? 🙂

**Comment by johnletey** [comment]
@nikitavoloboev I’m so sorry, I became extremely busy after that. Unfortunately, I don’t have much time to work on this until mid April.

Sorry for any inconvenience ... I’ll definitely have an efficient tool up and running by the end of April. I’ll keep you posted when I start working on it

**Comment by nikitavoloboev** [comment]
No worries :)

**Comment by johnletey** [comment]
@nikitavoloboev I've converted my code into a command line tool ... I'm going to see what I can do about speeding it up

[johnletey/dl-imgs](https://github.com/johnletey/dl-imgs)

**Comment by nikitavoloboev** [comment]
Sweet. Let me know when you push that change so I can try run it on this repo. :)

**Comment by johnletey** [comment]
Will do

**Comment by johnletey** [comment]
@nikitavoloboev Done. It's blazing fast now! Feel free to try it out

**Comment by nikitavoloboev** [comment]
holy shit that was fast 🤯

Well done!

**Comment by johnletey** [comment]
@nikitavoloboev Thanks!

**Pull request merged**
