### PR TITLE
api compilers microservices kubernetes other rust-libraries swift-lib…

### PR DESCRIPTION
**Pull request by Tuesday-Monday**
…raries hashing marketing tools (#1)

Co-authored-by: Nikita Voloboev <nikita.voloboev@gmail.com>

### Changes

- 
-

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
just curious what are you trying to achieve here? :)

**Comment by Tuesday-Monday** [comment]
Please disregard. I'm new to Git. I was trying to keep the fork up-to-date with yours. I have more to learn. Great job on the wiki!

**Comment by nikitavoloboev** [comment]
take a look here: https://stackoverflow.com/questions/24815952/git-pull-from-another-repository

so it will be

```
git remote add upstream https://github.com/nikitavoloboev/knowledge
```

Then any time you want to update your repo with my changes you run:

`git pull upstream`

**Comment by Tuesday-Monday** [comment]
Thank you, it worked perfectly! I just had to add "master"

`git pull upstream master`

**Pull request closed without merging**
